apiVersion: v1
kind: Namespace
metadata:
  name: load-tester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
        image: yondulab/load-tester-frontend:v0.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: load-tester
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi 
        image: yondulab/load-tester-backend:v0.7
        ports:
        - containerPort: 8080
      - name: redis
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: load-tester
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080  
    targetPort: 8080
  - name: redis
    port: 6379
    targetPort: 6379  
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-generator
  namespace: load-tester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-generator
  template:
    metadata:
      labels:
        app: cpu-generator
    spec:
      containers:
      - name: cpu-generator
        image: yondulab/load-tester-cpu-generator:v0.6
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-generator
  namespace: load-tester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-generator
  template:
    metadata:
      labels:
        app: memory-generator
    spec:
      containers:
      - name: memory-generator
        image: yondulab/load-tester-memory-generator:v0.2
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 1280Mi
